# Use root/example as user/password credentials

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: leminkhoa
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: crm
    ports:
      - "5432:5432"
